language: node_js

install:
  - npm install

script:
  - npm test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  
deploy:
 provider: script
 skip_cleanup: true
 script: .travis/pu.sh
 on:
   branch: master
   tags: false

