language: node_js
node_js:
  - 6

install:
  - npm install

before_script:
  - git config --global user.email "cfpbdeploybot@cfpb.gov"
  - git config --global user.name "cfpbdeploybot"
  - git config --global push.default matching
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_API_KEY}:@github.com" > .git/credentials

script:
  - npm test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  
deploy:
 - provider: script
   skip_cleanup: true
   script: npm version patch -m "[skip ci] Releasing, upgrading the version to %s"
   on:
     branch: master
     tags: false
 - provider: script
   skip_cleanup: true
   script: git push origin HEAD:$TRAVIS_BRANCH
   on:
     branch: master
     tags: false
 - provider: script
   skip_cleanup: true
   script: git push --tags
   on:
     branch: master
     tags: false
