name: ci

on: pull_request

jobs:

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set up Node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16.x

      - name: Install Node dependencies
        run: |
          yarn install

      - name: Lint the source code
        run: yarn run lint

      - name: Run front-end unit tests
        run: yarn run test

      - name: Update Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Start local website server
        run: |
          yarn start &
          sleep 5

      - name: Run browser tests
        run: yarn run cypress run
