name: ci

on: pull_request

jobs:

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set up Node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14.x

      - name: Install Node dependencies
        run: |
          yarn install

      - name: Lint the source code
        run: yarn run lint

      - name: Run front-end unit tests
        run: yarn run test

      - name: Update Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.6

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Set up Node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14.x

      - name: Install Node dependencies
        run: |
          yarn install

      - name: Run back-end tests
        run: |
          tox
